### ISSUE TITLE
Github Browser failing on even new installs

### ISSUE THREAD

**Issue by tanooki2017** [tvaddonsco/plugin.git.browser#18]
Hi.

the Github browser used to work for me untill i installed a radio addon. since then I get an error the moment I try to open up Github browser.   here are the details:

05:26:25.108 T:3420   ERROR: C:\Users\MediaYoozer\AppData\Roaming\Kodi\addons\plugin.git.browser\commoncore\beautifulsoup\bs4\element.py:16: UserWarning: The soupsieve package is not installed. CSS selectors cannot be used.
                                              'The soupsieve package is not installed. CSS selectors cannot be used.'
05:26:25.130 T:3420   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: function takes at most 2 arguments (3 given)
                                            Traceback (most recent call last):
                                              File "C:\Users\MediaYoozer\AppData\Roaming\Kodi\addons\plugin.git.browser\addon.py", line 403, in <module>
                                                if __name__ == '__main__': kodi.run()
                                              File "C:\Users\MediaYoozer\AppData\Roaming\Kodi\addons\plugin.git.browser\commoncore\kodi\runner.py", line 127, in run
                                                __dispatcher[args['mode']](*__args[args['mode']], **__kwargs[args['mode']])
                                              File "C:\Users\MediaYoozer\AppData\Roaming\Kodi\addons\plugin.git.browser\commoncore\kodi\runner.py", line 79, in func
                                                _func()
                                              File "C:\Users\MediaYoozer\AppData\Roaming\Kodi\addons\plugin.git.browser\addon.py", line 23, in main
                                                show_about()
                                              File "C:\Users\MediaYoozer\AppData\Roaming\Kodi\addons\plugin.git.browser\addon.py", line 370, in show_about
                                                kodi.dialog_textbox('GitHub Browser Instructions', text)
                                              File "C:\Users\MediaYoozer\AppData\Roaming\Kodi\addons\plugin.git.browser\commoncore\kodi\ui.py", line 84, in dialog_textbox
                                                return dialog.textviewer(heading, message, usemono)
                                            TypeError: function takes at most 2 arguments (3 given)
                                            -->End of Python script error report<--
05:26:25.225 T:340   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.git.browser/
05:26:25.225 T:340   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.git.browser/) failed

Now here is the odd part. I went and wiped out Kodi, deleted the kodi folder that contains my addons and saved settings, and reinstalled kodi.

I went through the usual procedures to install the TVA repo and install Github browser. I still get the same error when opening up Github browser on a fresh kodi install.

My device is a Windows PC running windows 8.1, AMD Phenom X4 with 16GB memory

Any ideas what happened and how I can get this working again?

**Comment by tvaddonsco** [comment]
Please provide Kodi log file so we can debug further @tanooki2017

**Comment by tvaddonsco** [comment]
Can we get a log please? @tanooki2017 

https://www.tvaddons.co/kodi-log-upload/
